# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
import numpy as np
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [5]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
matriz = np.arange(1,21).reshape(4,5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
matriz[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
ejercicio_5 = matriz[:2, :2]
print(ejercicio_5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [15]:
ejercicio_6 = matriz[::2, ::2]
print(ejercicio_6)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [18]:
ejercicio_7 = matriz[:-1:, ::-1]
print(ejercicio_7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [ ]:
[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [19]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)
x =="Loro"

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


array([ True, False, False,  True, False])

In [20]:
ejercicio_8 = x == "Loro"
print(x[ejercicio_8])

['Loro' 'Loro']


In [21]:
ejer_8_1 = np.where(x == "Loro")
x[ejer_8_1]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [23]:
x = np.arange(1,21).reshape(2,5,2)
print(x)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [24]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
ejer_10 = matriz[::-1,::-1]
print(ejer_10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [27]:
ejer_11 = np.zeros(10)
print(ejer_11)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
print(ejer_11.itemsize)
print(ejer_11.nbytes)

8
80


In [29]:
ejer_11[3]=1
print(ejer_11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [30]:
ejer_12 = np.arange(10,50)
print(ejer_12)
print(ejer_12[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [31]:
vector = np.array([1,2,0,0,4,0])
np.where(vector != 0)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [33]:
from random import randint

ejer_14 = np.random.randint(0,100, size=(1,10,10))
print(ejer_14)

[[[18 94 99 14 80 28 19  4 18 11]
  [32 63 39 38 20 19 46 10 45  8]
  [10 90 26 11 84  8 26 41 60 35]
  [44 71 35 58 34 59 37 37 94 42]
  [18 81 91  0 25 63 93  0 14 58]
  [89 30 11 26 13 22 36 14 94 17]
  [62 56 54 28 57  2 55 86 84 59]
  [94 16 94 59 88 34 41 16 62 39]
  [37 98 75 71 76  8 11 63 51 92]
  [10 24 66 73 95 46 47 75 51 62]]]


In [34]:
print(ejer_14.min())
print(np.max(ejer_14))

0
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [36]:
ejer_15 = np.random.random(30)
print(ejer_15)
print(ejer_15.mean())

[0.76605112 0.53713332 0.01598493 0.93054837 0.5705165  0.35109982
 0.0418295  0.98539226 0.37913418 0.11563298 0.22813791 0.56033667
 0.03350423 0.52707412 0.45358595 0.94887436 0.84626343 0.34143376
 0.65685856 0.89832034 0.82833658 0.44854018 0.08146013 0.71399873
 0.06568876 0.60995995 0.48889689 0.26017359 0.50353569 0.59111473]
0.4926472519989326


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [46]:
ejer_16 = np.ones((8,4)) 

ejer_16[1:-1, 1:-1] = 0 

print(ejer_16)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [47]:
np.int8

ejer_17 = np.zeros((8,8), np.int8)
ejer_17[1::2, ::2] = 1
ejer_17[::2, 1::2] = 1
print(ejer_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [48]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
x


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [49]:
ejer_19 = np.random.randint(1, 50, (5,5))

ejer_19 = (ejer_19 - np.mean(ejer_19))/np.std(ejer_19)
print(ejer_19)

[[ 1.38564467 -0.61769702 -0.9515873   1.21869953  1.13522696]
 [ 1.46911724 -0.70116959  0.21702868 -0.1168616  -1.20200501]
 [ 0.46744639 -0.03338903 -0.28380674 -1.11853244 -1.45242273]
 [-0.61769702 -0.45075188  0.05008354  2.22037037  1.13522696]
 [-0.03338903  1.13522696 -0.61769702 -1.45242273 -0.78464216]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [50]:
ejer_20 = np.arange(11)
print(ejer_20)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [52]:
ejer_20[3:9] = -1
print(ejer_20)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [53]:
ejer_20[3:9] = False
print(ejer_20)

[ 0  1  2  0  0  0  0  0  0  9 10]


In [54]:
x = np.arange(11)
y = x.copy()
y[(y > 3) & (y <= 8)] *= -1
print(y)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.