# Ejercicios Numpy I

Sirvan estos ejercicios para que fortalezcáis aquellos conceptos más importantes.

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
np.__version__

'1.20.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [13]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
array_true = np.full((3,3), True)
array_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [5]:
my_array = ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in  my_array:
    if i%2 != 0:
        print(i)

1
3
5
7
9


In [17]:

impares_array = my_array[my_array % 2 == 1]
impares_array

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [18]:
impares_array[:] = -1
impares_array

array([-1, -1, -1, -1, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [20]:
np.where(my_array % 2 ==1, -1, my_array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [27]:
import numpy as np
my_array.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [30]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b )

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [2]:

import numpy as np
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [10]:
my_array= np.arange(10)
new_array = my_array*10
print(new_array)
print(new_array[0])
print(new_array[-1])
print(new_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
90
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [12]:
my_matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [13]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [16]:
np.arange(4,1,-0.25)

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen `numpy.png` que encontrarás en la carpeta **img**

In [17]:
from skimage.io import imread
import matplotlib.pyplot as plt

imagen = imread("./img/numpy.png")
print(type(imagen))
print(imagen.shape)

plt.imshow(imagen)

FileNotFoundError: No such file: 'c:\Users\Karina\Desktop\data_science_apr_2021\clase1_data_science\week4_EDA_np_pd_json_apis_regex\day1_numpy_pandas_I\theory\numpy\Entregable_Numpy\img\numpy.png'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [18]:
ejercicio_17 = np.array([[1],[2],[3],[4]])
ejercicio_17

array([[1],
       [2],
       [3],
       [4]])

In [19]:
ejercicio_17.reshape((2,2))

array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [21]:
from random import randint
ejercicio_18 = np.random.randint(0,10, size =(4,5,3))
ejercicio_18

array([[[6, 6, 2],
        [7, 1, 0],
        [6, 3, 4],
        [3, 0, 5],
        [7, 7, 2]],

       [[9, 4, 1],
        [5, 4, 2],
        [1, 2, 2],
        [7, 6, 6],
        [8, 4, 3]],

       [[1, 1, 4],
        [4, 7, 5],
        [4, 5, 3],
        [8, 3, 3],
        [7, 3, 0]],

       [[2, 2, 3],
        [2, 2, 4],
        [2, 9, 1],
        [2, 3, 4],
        [0, 6, 4]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [25]:
x= np.full((10,1), False)
x 

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [28]:
x.reshape((2,5))


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [30]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x)
print(x.size)
print(x.ndim)
print(x.shape)


[[[16 12 19 18 18 12]
  [16 15 18 14 13 17]]

 [[12 11 15 13 10 16]
  [10 11 18 18 12 18]]

 [[11 16 12 16 15 14]
  [18 10 12 12 18 17]]

 [[17 15 10 10 13 10]
  [13 11 13 12 11 10]]

 [[14 18 14 10 12 10]
  [14 14 11 18 19 14]]]
60
3
(5, 2, 6)
