In [9]:
### matriz de 10x10 dimensiones

import numpy as np
tablero = np.zeros((10,10),np.int8)
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [8]:
## programa para crear estado inicial 

### de esta forma, puedo mostrar donde estan mis barcos

###preguntar posiciones de la flota

tablero[7:8,:2] = 1
print(tablero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
###Para saber quién empieza a jugar, los jugadores deberán ponerse de acuerdo para que uno de ellos sea el que llame a una función que devuelva dos valores random del 1 al 6, de tipo entero. El primer valor que se muestre por pantalla será el correspondiente al jugador que llama a la función, el segundo será el del contrincante. Quien saque un valor más alto, empieza.


In [ ]:

"""Bonus track. Mini hundir la flota
Crea un tablero de 10x10 relleno del carácter espacio ( ).
Posiciona un par de barcos en (0,1), (1,1) y (1,3), (1,4), (1,5), (1,6). Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora (TAMAÑO TOTAL) y otro de cuatro.
Recibe un disparo en uno de los barcos, sustituyendo la O por una X
Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.
TIP apartado 5: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones (5,0), (5,1), (5,2), (5,3). Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. Ojo con las posiciones donde ya hay barco!!!

Usa import random para elegir las coordenadas aleatorias.
Usa import random para elegir las coordenadas aleatorias."""

In [54]:
##tablero
for filas in range(10):
    print("_|" * 10)
    

_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
_|_|_|_|_|_|_|_|_|_|
9


In [55]:
import numpy as np
tablero = np.full(fill_value = ' ', shape = (10, 10))


# Barco 1
tablero[0:2, 1] = 'O'

# Barco 2
tablero[1, 3:7] = 'O'

# Disparo
tablero[0, 1] = 'X'

# Agua
tablero[0, 0] = '-'

print(tablero)

[['-' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
